# Copyright 2017 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Distributed benchmark configs to run with continuous build.
# For each benchmark, the following properties are supported:
#
# benchmark_name: (required) unique name of the benchmark to run
# args: (optional) argument values to pass to the benchmark.
# env_vars: (optional) environment variables to set for benchmark jobs.
# worker_count: (required) number of worker jobs to run
# ps_count: (required) number of ps jobs to run.
# gpus_per_machine: (optional) number of required gpus per worker
#   (currently only supporting <= 1).
# docker_file: (required) docker file to build a docker image for.
#   Path to the docker file should be relative to Jenkins build folder.
#   'benchmarks' github repo will be cloned to 'benchmarks' folder.
#
# Example:
# - benchmark_name: "benchmark_alexnet"
#   args:
#     data_format: "NHWC"
#   worker_count: 1
#   ps_count: 2
#   docker_file: "benchmarks/models/Dockerfile.alexnet_distributed_test"

- benchmark_name: "tf_cnn_benchmark_resnet50"
  args:
    data_format: "NHWC"
    model: "resnet50"
    result_storage: "cbuild_benchmark_datastore"
    num_gpus: 8
    local_parameter_device: "cpu"
  worker_count: 2
  ps_count: 2
  gpus_per_machine: 8
  docker_file: "benchmarks/scripts/Dockerfile.tf_cnn_benchmarks"
